export const TASKS = [
  { id: 1, name: 'Wake up and get out of bed' },
  { id: 2, name: 'Brush your teeth' },
  { id: 3, name: 'Take a shower' },
  { id: 4, name: 'Have breakfast' },
  { id: 5, name: 'Check emails' },
  { id: 6, name: 'Go for a walk' },
  { id: 7, name: 'Work on a project' },
  { id: 8, name: 'Read a book' },
  { id: 9, name: 'Exercise' },
  { id: 10, name: 'Prepare dinner' },
  { id: 11, name: 'Watch a movie' },
  { id: 12, name: 'Call a friend or family member' },
  { id: 13, name: 'Do the dishes' },
  { id: 14, name: 'Plan your next day' },
  { id: 15, name: 'Listen to music' },
  { id: 16, name: 'Grocery shopping' },
  { id: 17, name: 'Take a break and relax' },
  { id: 18, name: 'Organize your workspace' },
  { id: 19, name: 'Go to bed and sleep' },
  { id: 20, name: 'Write in a journal' },
  { id: 21, name: 'Check the news' },
  { id: 22, name: 'Water the plants' },
  { id: 23, name: 'Meditate' },
  { id: 24, name: 'Pay the bills' },
  { id: 25, name: 'Play a game' },
  { id: 26, name: 'Learn something new' },
  { id: 27, name: 'Take out the trash' },
  { id: 28, name: 'Cook a new recipe' },
  { id: 29, name: 'Write a to-do list' },
  { id: 30, name: 'Take a coffee break' },
  { id: 31, name: 'Hug someone you love' },
  { id: 32, name: 'Go for a run' },
  { id: 33, name: 'Shop for new clothes' },
  { id: 34, name: 'Plan a weekend getaway' },
  { id: 35, name: 'Check social media' },
  { id: 36, name: 'Visit a local museum' },
  { id: 37, name: "Fix something that's broken" },
  { id: 38, name: 'Learn a new language' },
  { id: 39, name: 'Volunteer for a cause' },
  { id: 40, name: 'Cook a special meal' },
  { id: 41, name: 'Read the news' },
  { id: 42, name: 'Visit a park' },
  { id: 43, name: 'Clean your car' },
  { id: 44, name: 'Listen to a podcast' },
  { id: 45, name: 'Take photos of the day' },
  { id: 46, name: 'Plan a home improvement project' },
  { id: 47, name: 'Watch a sunset' },
  { id: 48, name: 'Write a thank-you note' },
  { id: 49, name: 'Organize your closet' },
  { id: 50, name: 'Do a random act of kindness' },
];
